config_map:
  - name: JBOSS_A_MQ_BROKER_URL
    value: tcp://{{ microservice.name }}-amq-tcp.{{ project }}.svc:61616
  - name: PROJECT_BURNDOWN_REPOSITORY_JDBC_URL
    value: jdbc:postgresql://postgresql.{{ product.name }}-database.svc:5432/{{ project }}-{{ microservice.name }}
  - name: JAEGER_SERVICE_NAME
    value: green-{{ microservice.name }}
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: jaeger-agent.{{ product.name }}-monitoring.svc:5778    
  - name: JAEGER_AGENT_HOST
    value: jaeger-agent.{{ product.name }}-monitoring.svc      