export JBOSS_A_MQ_BROKER_URL=tcp://localhost:61616
export JBOSS_A_MQ_BROKER_USER=estafet
export JBOSS_A_MQ_BROKER_PASSWORD=estafet

export PROJECT_BURNDOWN_REPOSITORY_JDBC_URL=jdbc:postgresql://localhost:5432/project-burndown
export PROJECT_BURNDOWN_REPOSITORY_DB_USER=postgres
export PROJECT_BURNDOWN_REPOSITORY_DB_PASSWORD=welcome1
export STORY_REPOSITORY_SERVICE_URI=http://localhost:8080/story-repository
export PROJECT_REPOSITORY_SERVICE_URI=http://localhost:8080/project-repository